### PR TITLE
fix some codes which are depend on override contain() of Array.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Hi guy,
I really appreciate tinymce-prevent-delete.

current the plugin has some problems as following:
* override the contains of Array class.
* depends on jQuery.

so i fix some code to apply my application using tinyMCE.
please confirm this PR.

**Comment by csga5000** [comment]
Thanks for the pull request.  Those are good changes to make.  I originally implemented this for my own application where I relied on those functions existing and what not, but I wanted to make this available for others so I posted but did not bother to make it work without the changes.

I'd accept your merge request, though I don't like that it is replacing the entire file.  This may be a line endings issue, could you have perhaps accidentally changed all line endings in this file from \r\n to \n or vice versa?

Additionally some lines you added use four spaces.  I'm not super opinionated about indentation (though I favor tabs as it allows for configuration of indentation size by preference, and in some cases can use slightly less space in the file), and since the rest of the file is already in tabs could you also change your lines to conform?

Thanks,
   Chase

**Comment by ghost** [comment]
Thank you for your comment.

> about new line code, 4spaces

sorry, I changed new line code, and made a mistake(4 spaces) on the JS file.
I'll re-make the PR as you commented.

Thanks.

**Comment by ghost** [comment]
i'm sorry for my late reply.
we decided to not use this plugin for our project for some reasons.

therefore, i will close this PR.

**Comment by csga5000** [comment]
Okay, cool.  Did you find a good alternative, or did you simply not use this kind of technology in your software?

**Comment by ghost** [comment]
i can't find a good alternative,,,so, we didn't use this plugin in our system, and changed business and system specification.

**Pull request closed without merging**
